import { Need } from './Need';
import { Offer } from './Offer';
import { PerformanceMetric } from './PerformanceMetric';
import { DevTaskStatus } from '../types/DevTaskStatus';

export interface SelfOrchestrationTask {
  taskId: string;
  
  /** High-level Product Owner goal input */
  poIntent: string;
  
  /** Atomic technical needs generated by LLM semantic decomposition */
  decomposedNeeds: Need[];
  
  /** Code implementation offers generated by LLM */
  generatedOffers: Offer[];
  
  /** Quality control deployment metric monitoring state */
  metricsState: PerformanceMetric[];
  
  /** Execution status of the dev loop */
  status: DevTaskStatus;
}
